version: '3.8'

services:
  db:
    image: postgres:15
    container_name: car_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin_car
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: club_roberts_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # <--- ESTA ES LA LÍNEA MÁGICA
volumes:
  postgres_data: