"""0006_comercios_asociados

Revision ID: 208ea0e312f5
Revises: 76b421c257e8
Create Date: 2026-06-29 20:20:59.074107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208ea0e312f5'
down_revision: Union[str, Sequence[str], None] = '76b421c257e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercios_asociados',
    sa.Column('id_comercio', sa.Integer(), nullable=False),
    sa.Column('nombre_fantasia', sa.String(length=150), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=True),
    sa.Column('beneficio_ofrecido', sa.String(length=200), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('id_usuario_acceso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_acceso'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comercio')
    )
    op.create_index(op.f('ix_comercios_asociados_id_comercio'), 'comercios_asociados', ['id_comercio'], unique=False)
    op.drop_index(op.f('idx_asistencias_fecha'), table_name='asistencias')
    op.create_index('idx_asistencias_fecha', 'asistencias', ['fecha_hora_ingreso'], unique=False, postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.drop_index(op.f('idx_audit_log_created_at'), table_name='audit_log')
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_foreign_key('fk_config_actualizado_por', 'configuracion_global', 'usuarios', ['actualizado_por'], ['id_usuario'], ondelete='SET NULL', use_alter=True)
    op.drop_index(op.f('idx_eventos_fecha'), table_name='eventos')
    op.create_index('idx_eventos_fecha', 'eventos', ['fecha_inicio'], unique=False, postgresql_ops={'fecha_inicio': 'DESC'})
    op.drop_index(op.f('idx_notificaciones_usuario_no_leidas'), table_name='notificaciones', postgresql_where='(leida = false)')
    op.create_index('idx_notificaciones_usuario_no_leidas', 'notificaciones', ['id_usuario', 'created_at'], unique=False, postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.create_foreign_key('fk_reservas_orden', 'reservas_instalaciones', 'ordenes', ['id_orden'], ['id_orden'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reservas_orden', 'reservas_instalaciones', type_='foreignkey')
    op.drop_index('idx_notificaciones_usuario_no_leidas', table_name='notificaciones', postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_notificaciones_usuario_no_leidas'), 'notificaciones', ['id_usuario', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(leida = false)')
    op.drop_index('idx_eventos_fecha', table_name='eventos', postgresql_ops={'fecha_inicio': 'DESC'})
    op.create_index(op.f('idx_eventos_fecha'), 'eventos', [sa.literal_column('fecha_inicio DESC')], unique=False)
    op.drop_constraint('fk_config_actualizado_por', 'configuracion_global', type_='foreignkey')
    op.drop_index('idx_audit_log_created_at', table_name='audit_log', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_audit_log_created_at'), 'audit_log', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_asistencias_fecha', table_name='asistencias', postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.create_index(op.f('idx_asistencias_fecha'), 'asistencias', [sa.literal_column('fecha_hora_ingreso DESC')], unique=False)
    op.drop_index(op.f('ix_comercios_asociados_id_comercio'), table_name='comercios_asociados')
    op.drop_table('comercios_asociados')
    # ### end Alembic commands ###
