"""agregar_presente_ausente_convocatoria

Revision ID: 5e5c11d73200
Revises: 7d7c6bc4933e
Create Date: 2026-07-16 20:27:01.568676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5c11d73200'
down_revision: Union[str, Sequence[str], None] = '7d7c6bc4933e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_asistencias_fecha'), table_name='asistencias')
    op.create_index('idx_asistencias_fecha', 'asistencias', ['fecha_hora_ingreso'], unique=False, postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.drop_index(op.f('idx_audit_log_created_at'), table_name='audit_log')
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_eventos_fecha'), table_name='eventos')
    op.create_index('idx_eventos_fecha', 'eventos', ['fecha_inicio'], unique=False, postgresql_ops={'fecha_inicio': 'DESC'})
    op.drop_index(op.f('idx_notificaciones_usuario_no_leidas'), table_name='notificaciones', postgresql_where='(leida = false)')
    op.create_index('idx_notificaciones_usuario_no_leidas', 'notificaciones', ['id_usuario', 'created_at'], unique=False, postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###
    
op.execute("""
    ALTER TABLE convocatorias
    DROP CONSTRAINT chk_estado_convocatoria;
    
    ALTER TABLE convocatorias
    ADD CONSTRAINT chk_estado_convocatoria
    CHECK (estado IN ('citado', 'confirmado', 'rechazado', 'presente', 'ausente'));
""")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notificaciones_usuario_no_leidas', table_name='notificaciones', postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_notificaciones_usuario_no_leidas'), 'notificaciones', ['id_usuario', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(leida = false)')
    op.drop_index('idx_eventos_fecha', table_name='eventos', postgresql_ops={'fecha_inicio': 'DESC'})
    op.create_index(op.f('idx_eventos_fecha'), 'eventos', [sa.literal_column('fecha_inicio DESC')], unique=False)
    op.drop_index('idx_audit_log_created_at', table_name='audit_log', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_audit_log_created_at'), 'audit_log', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_asistencias_fecha', table_name='asistencias', postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.create_index(op.f('idx_asistencias_fecha'), 'asistencias', [sa.literal_column('fecha_hora_ingreso DESC')], unique=False)
    # ### end Alembic commands ###
