"""sync convocatorias columns

Revision ID: 7d7c6bc4933e
Revises: 90885e41b585
Create Date: 2026-07-16 16:29:00.699179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d7c6bc4933e'
down_revision: Union[str, Sequence[str], None] = '90885e41b585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_asistencias_fecha'), table_name='asistencias')
    op.create_index('idx_asistencias_fecha', 'asistencias', ['fecha_hora_ingreso'], unique=False, postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.drop_index(op.f('idx_audit_log_created_at'), table_name='audit_log')
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.alter_column('categorias_deportivas', 'fecha_corte_min',
               existing_type=sa.DATE(),
               comment='Fecha de nacimiento mínima (inclusive) admitida en la categoría. Se usa junto a fecha_corte_max para el autocompletado masivo del plantel.',
               existing_comment='Fecha de nacimiento mínima (inclusive) admitida en la categoría. Junto a fecha_corte_max define el rango que usa el autocompletado masivo.',
               existing_nullable=True)
    op.alter_column('categorias_deportivas', 'fecha_corte_max',
               existing_type=sa.DATE(),
               comment='Fecha de nacimiento máxima (inclusive) admitida en la categoría. NULL en cualquiera de los dos cortes desactiva el botón Autocompletar para esta categoría en el frontend.',
               existing_comment='Fecha de nacimiento máxima (inclusive) admitida en la categoría. NULL en cualquiera de los dos cortes desactiva el botón Autocompletar.',
               existing_nullable=True)
    op.add_column('convocatorias', sa.Column('citado_por', sa.Integer(), nullable=True, comment='Técnico/admin que arma la convocatoria.'))
    op.add_column('convocatorias', sa.Column('citado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('convocatorias', sa.Column('respondido_at', sa.DateTime(timezone=True), nullable=True, comment="Cuándo el jugador confirmó/rechazó. NULL mientras sigue en 'citado'."))
    op.add_column('convocatorias', sa.Column('notas', sa.Text(), nullable=True))
    op.alter_column('convocatorias', 'estado',
               existing_type=sa.VARCHAR(length=20),
               comment="'citado' | 'confirmado' | 'rechazado' | 'ausente' | 'presente'.",
               existing_nullable=False,
               existing_server_default=sa.text("'citado'::character varying"))
    op.create_index('idx_convocatorias_estado', 'convocatorias', ['estado'], unique=False)
    op.create_index('idx_convocatorias_evento', 'convocatorias', ['id_evento'], unique=False)
    op.create_foreign_key(None, 'convocatorias', 'usuarios', ['citado_por'], ['id_usuario'], ondelete='SET NULL')
    op.drop_column('convocatorias', 'updated_at')
    op.drop_column('convocatorias', 'created_at')
    op.drop_index(op.f('idx_eventos_fecha'), table_name='eventos')
    op.create_index('idx_eventos_fecha', 'eventos', ['fecha_inicio'], unique=False, postgresql_ops={'fecha_inicio': 'DESC'})
    op.drop_index(op.f('idx_notificaciones_usuario_no_leidas'), table_name='notificaciones', postgresql_where='(leida = false)')
    op.create_index('idx_notificaciones_usuario_no_leidas', 'notificaciones', ['id_usuario', 'created_at'], unique=False, postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.alter_column('usuarios', 'es_becado',
               existing_type=sa.BOOLEAN(),
               comment='TRUE = el socio está becado. El motor financiero ignora mes_cubierto_hasta y devuelve deuda = 0 mientras la beca esté activa. La deuda real queda congelada en mes_cubierto_hasta: cuando la beca expire, el sistema retoma el estado financiero desde donde estaba.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('usuarios', 'becado_hasta',
               existing_type=sa.DATE(),
               comment='NULL = beca indefinida (no expira). Si tiene fecha: la beca es válida hasta ese día inclusive. Condición activa: es_becado IS TRUE AND (becado_hasta IS NULL OR becado_hasta >= HOY).',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'becado_hasta',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='NULL = beca indefinida (no expira). Si tiene fecha: la beca es válida hasta ese día inclusive. Condición activa: es_becado IS TRUE AND (becado_hasta IS NULL OR becado_hasta >= HOY).',
               existing_nullable=True)
    op.alter_column('usuarios', 'es_becado',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE = el socio está becado. El motor financiero ignora mes_cubierto_hasta y devuelve deuda = 0 mientras la beca esté activa. La deuda real queda congelada en mes_cubierto_hasta: cuando la beca expire, el sistema retoma el estado financiero desde donde estaba.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_notificaciones_usuario_no_leidas', table_name='notificaciones', postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_notificaciones_usuario_no_leidas'), 'notificaciones', ['id_usuario', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(leida = false)')
    op.drop_index('idx_eventos_fecha', table_name='eventos', postgresql_ops={'fecha_inicio': 'DESC'})
    op.create_index(op.f('idx_eventos_fecha'), 'eventos', [sa.literal_column('fecha_inicio DESC')], unique=False)
    op.add_column('convocatorias', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('convocatorias', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'convocatorias', type_='foreignkey')
    op.drop_index('idx_convocatorias_evento', table_name='convocatorias')
    op.drop_index('idx_convocatorias_estado', table_name='convocatorias')
    op.alter_column('convocatorias', 'estado',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="'citado' | 'confirmado' | 'rechazado' | 'ausente' | 'presente'.",
               existing_nullable=False,
               existing_server_default=sa.text("'citado'::character varying"))
    op.drop_column('convocatorias', 'notas')
    op.drop_column('convocatorias', 'respondido_at')
    op.drop_column('convocatorias', 'citado_at')
    op.drop_column('convocatorias', 'citado_por')
    op.alter_column('categorias_deportivas', 'fecha_corte_max',
               existing_type=sa.DATE(),
               comment='Fecha de nacimiento máxima (inclusive) admitida en la categoría. NULL en cualquiera de los dos cortes desactiva el botón Autocompletar.',
               existing_comment='Fecha de nacimiento máxima (inclusive) admitida en la categoría. NULL en cualquiera de los dos cortes desactiva el botón Autocompletar para esta categoría en el frontend.',
               existing_nullable=True)
    op.alter_column('categorias_deportivas', 'fecha_corte_min',
               existing_type=sa.DATE(),
               comment='Fecha de nacimiento mínima (inclusive) admitida en la categoría. Junto a fecha_corte_max define el rango que usa el autocompletado masivo.',
               existing_comment='Fecha de nacimiento mínima (inclusive) admitida en la categoría. Se usa junto a fecha_corte_max para el autocompletado masivo del plantel.',
               existing_nullable=True)
    op.drop_index('idx_audit_log_created_at', table_name='audit_log', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_audit_log_created_at'), 'audit_log', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_asistencias_fecha', table_name='asistencias', postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.create_index(op.f('idx_asistencias_fecha'), 'asistencias', [sa.literal_column('fecha_hora_ingreso DESC')], unique=False)
    # ### end Alembic commands ###
