"""sincronizar_base_neon

Revision ID: 90885e41b585
Revises: d8a4662bbaa0
Create Date: 2026-07-06 09:35:58.020147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90885e41b585'
down_revision: Union[str, Sequence[str], None] = 'd8a4662bbaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercios_asociados',
    sa.Column('id_comercio', sa.Integer(), nullable=False),
    sa.Column('nombre_fantasia', sa.String(length=150), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=True),
    sa.Column('beneficio_ofrecido', sa.String(length=200), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('id_usuario_acceso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_acceso'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comercio')
    )
    op.create_index(op.f('ix_comercios_asociados_id_comercio'), 'comercios_asociados', ['id_comercio'], unique=False)
    op.alter_column('asistencias', 'metodo',
               existing_type=sa.VARCHAR(length=10),
               comment="'QR' = escaneo de código. 'DNI' = búsqueda manual por DNI.",
               existing_nullable=False)
    op.alter_column('asistencias', 'registrado_por',
               existing_type=sa.INTEGER(),
               comment='DNI del operador que hizo el escaneo.',
               existing_nullable=False)
    op.alter_column('asistencias', 'estado_financiero_snapshot',
               existing_type=sa.VARCHAR(length=20),
               comment="Snapshot al momento del ingreso: 'al_dia' | 'moroso'.",
               existing_nullable=False)
    op.drop_index(op.f('idx_asistencias_fecha'), table_name='asistencias')
    op.create_index('idx_asistencias_fecha', 'asistencias', ['fecha_hora_ingreso'], unique=False, postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.drop_table_comment(
        'asistencias',
        existing_comment='Registro inmutable de ingresos. El campo estado_financiero_snapshot guarda el estado al momento del escaneo.',
        schema=None
    )
    op.alter_column('audit_log', 'accion',
               existing_type=sa.VARCHAR(length=100),
               comment='Ej: APROBAR_ORDEN, CAMBIO_ROL, BAJA_USUARIO, LOGIN_FALLIDO',
               existing_nullable=False)
    op.alter_column('audit_log', 'detalle',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Estructura: {"antes": {...}, "despues": {...}}',
               existing_nullable=True)
    op.drop_index(op.f('idx_audit_log_created_at'), table_name='audit_log')
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_table_comment(
        'audit_log',
        existing_comment='Tabla de solo escritura. Nunca se actualiza ni elimina. Trazabilidad completa del sistema.',
        schema=None
    )
    op.alter_column('configuracion_global', 'valor_cuota_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Precio vigente de la cuota. Modifica este campo y toda la deuda se recalcula.',
               existing_comment='Al modificar este campo, la deuda de todos los morosos se recalcula dinámicamente.',
               existing_nullable=False)
    op.alter_column('configuracion_global', 'dia_vencimiento_cuota',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Día del mes en que vence el período de cobertura del socio (1–28). Por ejemplo: 10 → el acceso del socio expira el día 10 de cada mes. Limitado a 28 para evitar fechas inexistentes en febrero.',
               existing_server_default=sa.text('10'))
    op.alter_column('configuracion_global', 'meses_antiguedad_beneficio',
               existing_type=sa.INTEGER(),
               comment='Meses requeridos para acceder al descuento por antigüedad.',
               existing_nullable=False,
               existing_server_default=sa.text('6'))
    op.alter_column('configuracion_global', 'descuento_beneficio',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Porcentaje (0–100) de descuento en alquileres por antigüedad.',
               existing_comment='Porcentaje (0-100) de descuento en alquiler de instalaciones por antigüedad.',
               existing_nullable=False,
               existing_server_default=sa.text('15'))
    op.drop_index(op.f('idx_configuracion_global_singleton'), table_name='configuracion_global')
    op.drop_table_comment(
        'configuracion_global',
        existing_comment='Cerebro financiero del sistema. Una sola fila. Solo el Admin General puede modificarla.',
        schema=None
    )
    op.alter_column('detalles_orden', 'precio_unitario_historico',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Precio congelado al momento de la compra.',
               existing_comment='CRÍTICO: al aprobar la orden, usar SIEMPRE este valor, nunca precio_actual del producto.',
               existing_nullable=False)
    op.alter_column('detalles_orden', 'mes_referencia',
               existing_type=sa.DATE(),
               comment='Para cuotas: primer día del mes pagado (ej: 2025-06-01 = Junio 2025).',
               existing_comment='Para cuotas: almacena el mes al que corresponde el pago (2025-06-01 = Junio 2025).',
               existing_nullable=True)
    op.alter_column('eventos', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               comment='partido | torneo | entrenamiento | institucional | otro',
               existing_nullable=False)
    op.drop_index(op.f('idx_eventos_fecha'), table_name='eventos')
    op.create_index('idx_eventos_fecha', 'eventos', ['fecha_inicio'], unique=False, postgresql_ops={'fecha_inicio': 'DESC'})
    op.alter_column('notificaciones', 'referencia_tabla',
               existing_type=sa.VARCHAR(length=60),
               comment="Nombre de la tabla relacionada: 'ordenes', 'eventos', etc.",
               existing_nullable=True)
    op.drop_index(op.f('idx_notificaciones_usuario_no_leidas'), table_name='notificaciones', postgresql_where='(leida = false)')
    op.create_index('idx_notificaciones_usuario_no_leidas', 'notificaciones', ['id_usuario', 'created_at'], unique=False, postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.alter_column('ordenes', 'id_pago',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Todo comprobante y verificación vive en el Pago, no acá.')
    op.alter_column('ordenes', 'motivo_rechazo',
               existing_type=sa.TEXT(),
               comment="Obligatorio cuando estado = 'rechazada'.",
               existing_comment='Requerido si estado = rechazada. El admin debe explicar por qué (ej: monto no coincide).',
               existing_nullable=True)
    op.alter_column('ordenes', 'expira_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Job programado marca como expirada y libera recursos al superar esta fecha.',
               existing_comment='Un job programado revisa periódicamente y marca como expirada las órdenes vencidas, liberando stock y reservas.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() + '48:00:00'::interval)"))
    op.create_index('idx_ordenes_pago', 'ordenes', ['id_pago'], unique=False)
    op.create_foreign_key(None, 'ordenes', 'pagos', ['id_pago'], ['id_pago'], ondelete='RESTRICT')
    op.drop_column('ordenes', 'comprobante_url')
    op.alter_column('pagos', 'estado',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=40),
               nullable=False,
               comment='pendiente | verificado | rechazado',
               existing_server_default=sa.text("'pendiente'::character varying"))
    op.alter_column('pagos', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('idx_pagos_estado', 'pagos', ['estado'], unique=False, postgresql_where=sa.text("estado = 'pendiente'"))
    op.create_index('idx_pagos_usuario', 'pagos', ['id_usuario'], unique=False)
    op.alter_column('productos_servicios', 'categoria',
               existing_type=sa.VARCHAR(length=50),
               comment='cuota_social | alquiler | indumentaria | otro',
               existing_nullable=False)
    op.alter_column('productos_servicios', 'stock',
               existing_type=sa.INTEGER(),
               comment='NULL = sin stock físico (servicios). Integer para indumentaria.',
               existing_comment='NULL para servicios sin stock físico (cuota social). Integer para indumentaria.',
               existing_nullable=True)
    op.alter_column('reservas_instalaciones', 'instalacion',
               existing_type=sa.VARCHAR(length=100),
               comment="Nombre físico: 'quincho', 'cancha_1', 'cancha_2', etc.",
               existing_nullable=False)
    op.drop_table_comment(
        'reservas_instalaciones',
        existing_comment='Una reserva se crea en estado bloqueada al generar la orden. Pasa a confirmada al aprobarla, y a liberada si se rechaza o expira.',
        schema=None
    )
    op.alter_column('roles', 'peso_jerarquico',
               existing_type=sa.INTEGER(),
               comment='Mayor número = mayor jerarquía. Admin General=100, Socio=10, Invitado=1.',
               existing_comment='Permite ordenar y comparar roles. Admin General = 100, Socio = 10, Invitado = 1.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('usuarios', 'dni',
               existing_type=sa.VARCHAR(length=10),
               comment='Clave de negocio inmutable.',
               existing_nullable=False)
    op.alter_column('usuarios', 'requiere_cambio_password',
               existing_type=sa.BOOLEAN(),
               comment='TRUE en primer ingreso. El frontend bloquea hasta que el socio cambie la clave.',
               existing_comment='TRUE para socios migrados desde Excel. El frontend bloquea navegación hasta que cambien la clave.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('usuarios', 'qr_token',
               existing_type=sa.UUID(),
               comment='Token opaco. El QR NUNCA contiene datos planos. Se rota al cambiar estado financiero.',
               existing_comment='Token opaco UUID. El QR nunca expone datos planos. Se rota al cambiar estado financiero.',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('usuarios', 'mes_cubierto_hasta',
               existing_type=sa.DATE(),
               comment="Fecha exacta hasta la cual el socio tiene el acceso habilitado. NULL = nunca pagó (socio nuevo o sin cuotas aprobadas). Evaluación de estado: CURRENT_DATE <= mes_cubierto_hasta → 'al_dia'. El backend calcula esta fecha al aprobar una orden de cuota_social:   nueva_fecha = MAX(mes_cubierto_hasta_actual, hoy)               + meses_pagados meses               con día = dia_vencimiento_cuota de ConfiguracionGlobal. Si el socio pagó por adelantado, queda inmune a aumentos de precio hasta esta fecha (el precio ya fue congelado en precio_unitario_historico).",
               existing_comment='Si pagó por adelantado, queda inmune a aumentos hasta esta fecha.',
               existing_nullable=True)
    op.alter_column('usuarios', 'deuda_historica_meses',
               existing_type=sa.INTEGER(),
               comment='Meses adeudados en cantidad, NUNCA en pesos.',
               existing_comment='Cantidad de meses adeudados. Deuda total = deuda_historica_meses × valor_cuota_base_vigente.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('usuarios', 'fecha_baja',
               existing_type=sa.DATE(),
               comment='NULL = activo. Registrar fecha al dar de baja, nunca borrar el registro.',
               existing_nullable=True)
    op.alter_column('usuarios', 'nombre_completo_search',
               existing_type=postgresql.TSVECTOR(),
               comment='Gestionado por trigger. No escribir desde el ORM.',
               existing_nullable=True)
    op.alter_column('usuarios_categorias', 'temporada',
               existing_type=sa.VARCHAR(length=10),
               comment="Año de la temporada. Ej: '2025'.",
               existing_nullable=False,
               existing_server_default=sa.text("to_char((CURRENT_DATE)::timestamp with time zone, 'YYYY'::text)"))
    op.alter_column('usuarios_roles', 'valido_hasta',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='NULL = permanente. Completar con cierre de evento para roles temporales.',
               existing_comment='Para admin_temporal: se completa con la fecha de cierre del evento. Job programado lo limpia.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios_roles', 'valido_hasta',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Para admin_temporal: se completa con la fecha de cierre del evento. Job programado lo limpia.',
               existing_comment='NULL = permanente. Completar con cierre de evento para roles temporales.',
               existing_nullable=True)
    op.alter_column('usuarios_categorias', 'temporada',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment="Año de la temporada. Ej: '2025'.",
               existing_nullable=False,
               existing_server_default=sa.text("to_char((CURRENT_DATE)::timestamp with time zone, 'YYYY'::text)"))
    op.alter_column('usuarios', 'nombre_completo_search',
               existing_type=postgresql.TSVECTOR(),
               comment=None,
               existing_comment='Gestionado por trigger. No escribir desde el ORM.',
               existing_nullable=True)
    op.alter_column('usuarios', 'fecha_baja',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='NULL = activo. Registrar fecha al dar de baja, nunca borrar el registro.',
               existing_nullable=True)
    op.alter_column('usuarios', 'deuda_historica_meses',
               existing_type=sa.INTEGER(),
               comment='Cantidad de meses adeudados. Deuda total = deuda_historica_meses × valor_cuota_base_vigente.',
               existing_comment='Meses adeudados en cantidad, NUNCA en pesos.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('usuarios', 'mes_cubierto_hasta',
               existing_type=sa.DATE(),
               comment='Si pagó por adelantado, queda inmune a aumentos hasta esta fecha.',
               existing_comment="Fecha exacta hasta la cual el socio tiene el acceso habilitado. NULL = nunca pagó (socio nuevo o sin cuotas aprobadas). Evaluación de estado: CURRENT_DATE <= mes_cubierto_hasta → 'al_dia'. El backend calcula esta fecha al aprobar una orden de cuota_social:   nueva_fecha = MAX(mes_cubierto_hasta_actual, hoy)               + meses_pagados meses               con día = dia_vencimiento_cuota de ConfiguracionGlobal. Si el socio pagó por adelantado, queda inmune a aumentos de precio hasta esta fecha (el precio ya fue congelado en precio_unitario_historico).",
               existing_nullable=True)
    op.alter_column('usuarios', 'qr_token',
               existing_type=sa.UUID(),
               comment='Token opaco UUID. El QR nunca expone datos planos. Se rota al cambiar estado financiero.',
               existing_comment='Token opaco. El QR NUNCA contiene datos planos. Se rota al cambiar estado financiero.',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('usuarios', 'requiere_cambio_password',
               existing_type=sa.BOOLEAN(),
               comment='TRUE para socios migrados desde Excel. El frontend bloquea navegación hasta que cambien la clave.',
               existing_comment='TRUE en primer ingreso. El frontend bloquea hasta que el socio cambie la clave.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('usuarios', 'dni',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Clave de negocio inmutable.',
               existing_nullable=False)
    op.alter_column('roles', 'peso_jerarquico',
               existing_type=sa.INTEGER(),
               comment='Permite ordenar y comparar roles. Admin General = 100, Socio = 10, Invitado = 1.',
               existing_comment='Mayor número = mayor jerarquía. Admin General=100, Socio=10, Invitado=1.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_table_comment(
        'reservas_instalaciones',
        'Una reserva se crea en estado bloqueada al generar la orden. Pasa a confirmada al aprobarla, y a liberada si se rechaza o expira.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('reservas_instalaciones', 'instalacion',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Nombre físico: 'quincho', 'cancha_1', 'cancha_2', etc.",
               existing_nullable=False)
    op.alter_column('productos_servicios', 'stock',
               existing_type=sa.INTEGER(),
               comment='NULL para servicios sin stock físico (cuota social). Integer para indumentaria.',
               existing_comment='NULL = sin stock físico (servicios). Integer para indumentaria.',
               existing_nullable=True)
    op.alter_column('productos_servicios', 'categoria',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='cuota_social | alquiler | indumentaria | otro',
               existing_nullable=False)
    op.drop_index('idx_pagos_usuario', table_name='pagos')
    op.drop_index('idx_pagos_estado', table_name='pagos', postgresql_where=sa.text("estado = 'pendiente'"))
    op.alter_column('pagos', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pagos', 'estado',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='pendiente | verificado | rechazado',
               existing_server_default=sa.text("'pendiente'::character varying"))
    op.add_column('ordenes', sa.Column('comprobante_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ordenes', type_='foreignkey')
    op.drop_index('idx_ordenes_pago', table_name='ordenes')
    op.alter_column('ordenes', 'expira_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Un job programado revisa periódicamente y marca como expirada las órdenes vencidas, liberando stock y reservas.',
               existing_comment='Job programado marca como expirada y libera recursos al superar esta fecha.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() + '48:00:00'::interval)"))
    op.alter_column('ordenes', 'motivo_rechazo',
               existing_type=sa.TEXT(),
               comment='Requerido si estado = rechazada. El admin debe explicar por qué (ej: monto no coincide).',
               existing_comment="Obligatorio cuando estado = 'rechazada'.",
               existing_nullable=True)
    op.alter_column('ordenes', 'id_pago',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Todo comprobante y verificación vive en el Pago, no acá.')
    op.drop_index('idx_notificaciones_usuario_no_leidas', table_name='notificaciones', postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_notificaciones_usuario_no_leidas'), 'notificaciones', ['id_usuario', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(leida = false)')
    op.alter_column('notificaciones', 'referencia_tabla',
               existing_type=sa.VARCHAR(length=60),
               comment=None,
               existing_comment="Nombre de la tabla relacionada: 'ordenes', 'eventos', etc.",
               existing_nullable=True)
    op.drop_index('idx_eventos_fecha', table_name='eventos', postgresql_ops={'fecha_inicio': 'DESC'})
    op.create_index(op.f('idx_eventos_fecha'), 'eventos', [sa.literal_column('fecha_inicio DESC')], unique=False)
    op.alter_column('eventos', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='partido | torneo | entrenamiento | institucional | otro',
               existing_nullable=False)
    op.alter_column('detalles_orden', 'mes_referencia',
               existing_type=sa.DATE(),
               comment='Para cuotas: almacena el mes al que corresponde el pago (2025-06-01 = Junio 2025).',
               existing_comment='Para cuotas: primer día del mes pagado (ej: 2025-06-01 = Junio 2025).',
               existing_nullable=True)
    op.alter_column('detalles_orden', 'precio_unitario_historico',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='CRÍTICO: al aprobar la orden, usar SIEMPRE este valor, nunca precio_actual del producto.',
               existing_comment='Precio congelado al momento de la compra.',
               existing_nullable=False)
    op.create_table_comment(
        'configuracion_global',
        'Cerebro financiero del sistema. Una sola fila. Solo el Admin General puede modificarla.',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_configuracion_global_singleton'), 'configuracion_global', [sa.literal_column('(true)')], unique=True)
    op.alter_column('configuracion_global', 'descuento_beneficio',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Porcentaje (0-100) de descuento en alquiler de instalaciones por antigüedad.',
               existing_comment='Porcentaje (0–100) de descuento en alquileres por antigüedad.',
               existing_nullable=False,
               existing_server_default=sa.text('15'))
    op.alter_column('configuracion_global', 'meses_antiguedad_beneficio',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Meses requeridos para acceder al descuento por antigüedad.',
               existing_nullable=False,
               existing_server_default=sa.text('6'))
    op.alter_column('configuracion_global', 'dia_vencimiento_cuota',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Día del mes en que vence el período de cobertura del socio (1–28). Por ejemplo: 10 → el acceso del socio expira el día 10 de cada mes. Limitado a 28 para evitar fechas inexistentes en febrero.',
               existing_server_default=sa.text('10'))
    op.alter_column('configuracion_global', 'valor_cuota_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Al modificar este campo, la deuda de todos los morosos se recalcula dinámicamente.',
               existing_comment='Precio vigente de la cuota. Modifica este campo y toda la deuda se recalcula.',
               existing_nullable=False)
    op.create_table_comment(
        'audit_log',
        'Tabla de solo escritura. Nunca se actualiza ni elimina. Trazabilidad completa del sistema.',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_audit_log_created_at', table_name='audit_log', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_audit_log_created_at'), 'audit_log', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('audit_log', 'detalle',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Estructura: {"antes": {...}, "despues": {...}}',
               existing_nullable=True)
    op.alter_column('audit_log', 'accion',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Ej: APROBAR_ORDEN, CAMBIO_ROL, BAJA_USUARIO, LOGIN_FALLIDO',
               existing_nullable=False)
    op.create_table_comment(
        'asistencias',
        'Registro inmutable de ingresos. El campo estado_financiero_snapshot guarda el estado al momento del escaneo.',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_asistencias_fecha', table_name='asistencias', postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.create_index(op.f('idx_asistencias_fecha'), 'asistencias', [sa.literal_column('fecha_hora_ingreso DESC')], unique=False)
    op.alter_column('asistencias', 'estado_financiero_snapshot',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Snapshot al momento del ingreso: 'al_dia' | 'moroso'.",
               existing_nullable=False)
    op.alter_column('asistencias', 'registrado_por',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='DNI del operador que hizo el escaneo.',
               existing_nullable=False)
    op.alter_column('asistencias', 'metodo',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment="'QR' = escaneo de código. 'DNI' = búsqueda manual por DNI.",
               existing_nullable=False)
    op.drop_index(op.f('ix_comercios_asociados_id_comercio'), table_name='comercios_asociados')
    op.drop_table('comercios_asociados')
    # ### end Alembic commands ###
