"""0001_initial_tables

Revision ID: c90509324888
Revises: 
Create Date: 2026-06-29 20:05:32.865476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c90509324888'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_deportivas',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('configuracion_global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_cuota_base', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio vigente de la cuota. Modifica este campo y toda la deuda se recalcula.'),
    sa.Column('meses_antiguedad_beneficio', sa.Integer(), server_default=sa.text('6'), nullable=False, comment='Meses requeridos para acceder al descuento por antigüedad.'),
    sa.Column('descuento_beneficio', sa.Numeric(precision=5, scale=2), server_default=sa.text('15'), nullable=False, comment='Porcentaje (0–100) de descuento en alquileres por antigüedad.'),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id_usuario'], name='fk_config_actualizado_por', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_servicios',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False, comment='cuota_social | alquiler | indumentaria | otro'),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True, comment='NULL = sin stock físico (servicios). Integer para indumentaria.'),
    sa.Column('es_activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("categoria IN ('cuota_social', 'alquiler', 'indumentaria', 'otro')", name='chk_producto_categoria'),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index('idx_productos_categoria', 'productos_servicios', ['categoria'], unique=False, postgresql_where=sa.text('es_activo = TRUE'))
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('peso_jerarquico', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Mayor número = mayor jerarquía. Admin General=100, Socio=10, Invitado=1.'),
    sa.Column('es_activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=10), nullable=False, comment='Clave de negocio inmutable.'),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('foto_perfil_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('requiere_cambio_password', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='TRUE en primer ingreso. El frontend bloquea hasta que el socio cambie la clave.'),
    sa.Column('ultimo_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_token', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Token opaco. El QR NUNCA contiene datos planos. Se rota al cambiar estado financiero.'),
    sa.Column('qr_generado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mes_cubierto_hasta', sa.Date(), nullable=True, comment='Si pagó por adelantado, queda inmune a aumentos hasta esta fecha.'),
    sa.Column('deuda_historica_meses', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Meses adeudados en cantidad, NUNCA en pesos.'),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True, comment='NULL = activo. Registrar fecha al dar de baja, nunca borrar el registro.'),
    sa.Column('is_directivo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('nombre_completo_search', postgresql.TSVECTOR(), nullable=True, comment='Gestionado por trigger. No escribir desde el ORM.'),
    sa.Column('id_titular', sa.Integer(), nullable=True),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deuda_historica_meses >= 0', name='chk_deuda_no_negativa'),
    sa.ForeignKeyConstraint(['id_titular'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index('idx_usuarios_apellido', 'usuarios', ['apellido'], unique=False)
    op.create_index('idx_usuarios_dni', 'usuarios', ['dni'], unique=False)
    op.create_index('idx_usuarios_fecha_baja', 'usuarios', ['fecha_baja'], unique=False, postgresql_where=sa.text('fecha_baja IS NULL'))
    op.create_index('idx_usuarios_qr_token', 'usuarios', ['qr_token'], unique=False)
    op.create_index('idx_usuarios_search', 'usuarios', ['nombre_completo_search'], unique=False, postgresql_using='gin')
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_actor', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False, comment='Ej: APROBAR_ORDEN, CAMBIO_ROL, BAJA_USUARIO, LOGIN_FALLIDO'),
    sa.Column('tabla_afectada', sa.String(length=60), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Estructura: {"antes": {...}, "despues": {...}}'),
    sa.Column('ip_origen', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_actor'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_accion', 'audit_log', ['accion'], unique=False)
    op.create_index('idx_audit_log_actor', 'audit_log', ['usuario_actor'], unique=False)
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_audit_log_tabla', 'audit_log', ['tabla_afectada', 'registro_id'], unique=False)
    op.create_table('eventos',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False, comment='partido | torneo | entrenamiento | institucional | otro'),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'programado'"), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('programado', 'en_curso', 'finalizado', 'cancelado')", name='chk_evento_estado'),
    sa.CheckConstraint("tipo IN ('partido', 'torneo', 'entrenamiento', 'institucional', 'otro')", name='chk_evento_tipo'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias_deportivas.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_index('idx_eventos_estado', 'eventos', ['estado'], unique=False, postgresql_where=sa.text("estado IN ('programado', 'en_curso')"))
    op.create_index('idx_eventos_fecha', 'eventos', ['fecha_inicio'], unique=False, postgresql_ops={'fecha_inicio': 'DESC'})
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=True),
    sa.Column('leida', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('referencia_tabla', sa.String(length=60), nullable=True, comment="Nombre de la tabla relacionada: 'ordenes', 'eventos', etc."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('orden_aprobada', 'orden_rechazada', 'cuota_vencida', 'reserva_confirmada', 'reserva_cancelada', 'rol_asignado', 'rol_removido', 'convocatoria_partido', 'sistema')", name='chk_notificacion_tipo'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_index('idx_notificaciones_usuario_no_leidas', 'notificaciones', ['id_usuario', 'created_at'], unique=False, postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.create_table('ordenes',
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.String(length=40), server_default=sa.text("'pendiente_verificacion'"), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comprobante_url', sa.Text(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True, comment="Obligatorio cuando estado = 'rechazada'."),
    sa.Column('aprobada_por', sa.Integer(), nullable=True),
    sa.Column('aprobada_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expira_at', sa.DateTime(timezone=True), server_default=sa.text("NOW() + INTERVAL '48 hours'"), nullable=False, comment='Job programado marca como expirada y libera recursos al superar esta fecha.'),
    sa.Column('notas_admin', sa.Text(), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente_verificacion','aprobada','rechazada','cancelada_socio','expirada')", name='chk_orden_estado'),
    sa.ForeignKeyConstraint(['aprobada_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_index('idx_ordenes_estado', 'ordenes', ['estado'], unique=False, postgresql_where=sa.text("estado = 'pendiente_verificacion'"))
    op.create_index('idx_ordenes_expira_at', 'ordenes', ['expira_at'], unique=False, postgresql_where=sa.text("estado = 'pendiente_verificacion'"))
    op.create_index('idx_ordenes_usuario', 'ordenes', ['id_usuario'], unique=False)
    op.create_table('reservas_instalaciones',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('instalacion', sa.String(length=100), nullable=False, comment="Nombre físico: 'quincho', 'cancha_1', 'cancha_2', etc."),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'bloqueada'"), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=True),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('bloqueada', 'confirmada', 'liberada', 'expirada')", name='chk_reserva_estado'),
    sa.CheckConstraint('fecha_fin > fecha_inicio', name='chk_reserva_fechas'),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes.id_orden'], name='fk_reservas_orden', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos_servicios.id_producto'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_index('idx_reservas_instalacion_tiempo', 'reservas_instalaciones', ['instalacion', 'fecha_inicio', 'fecha_fin'], unique=False, postgresql_where=sa.text("estado IN ('bloqueada', 'confirmada')"))
    op.create_table('usuarios_categorias',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('temporada', sa.String(length=10), server_default=sa.text("TO_CHAR(CURRENT_DATE, 'YYYY')"), nullable=False, comment="Año de la temporada. Ej: '2025'."),
    sa.Column('es_capitan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias_deportivas.id_categoria'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_categoria', 'temporada')
    )
    op.create_table('usuarios_roles',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('valido_hasta', sa.DateTime(timezone=True), nullable=True, comment='NULL = permanente. Completar con cierre de evento para roles temporales.'),
    sa.Column('asignado_por', sa.Integer(), nullable=True),
    sa.Column('asignado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol')
    )
    op.create_index('idx_usuarios_roles_expiry', 'usuarios_roles', ['valido_hasta'], unique=False, postgresql_where=sa.text('valido_hasta IS NOT NULL'))
    op.create_index('idx_usuarios_roles_usuario', 'usuarios_roles', ['id_usuario'], unique=False)
    op.create_table('asistencias',
    sa.Column('id_asistencia', sa.BigInteger(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_ingreso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metodo', sa.String(length=10), nullable=False, comment="'QR' = escaneo de código. 'DNI' = búsqueda manual por DNI."),
    sa.Column('registrado_por', sa.Integer(), nullable=False, comment='DNI del operador que hizo el escaneo.'),
    sa.Column('estado_financiero_snapshot', sa.String(length=20), nullable=False, comment="Snapshot al momento del ingreso: 'al_dia' | 'moroso'."),
    sa.CheckConstraint("estado_financiero_snapshot IN ('al_dia', 'moroso')", name='chk_asistencia_snapshot'),
    sa.CheckConstraint("metodo IN ('QR', 'DNI')", name='chk_asistencia_metodo'),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    op.create_index('idx_asistencias_evento', 'asistencias', ['id_evento'], unique=False)
    op.create_index('idx_asistencias_fecha', 'asistencias', ['fecha_hora_ingreso'], unique=False, postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.create_index('idx_asistencias_usuario', 'asistencias', ['id_usuario'], unique=False)
    op.create_table('detalles_orden',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('precio_unitario_historico', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio congelado al momento de la compra.'),
    sa.Column('mes_referencia', sa.Date(), nullable=True, comment='Para cuotas: primer día del mes pagado (ej: 2025-06-01 = Junio 2025).'),
    sa.Column('id_reserva', sa.Integer(), nullable=True),
    sa.CheckConstraint('cantidad > 0', name='chk_detalle_cantidad_positiva'),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes.id_orden'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos_servicios.id_producto'], ),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas_instalaciones.id_reserva'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index('idx_detalles_orden_orden', 'detalles_orden', ['id_orden'], unique=False)
    op.create_index('idx_detalles_orden_producto', 'detalles_orden', ['id_producto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_detalles_orden_producto', table_name='detalles_orden')
    op.drop_index('idx_detalles_orden_orden', table_name='detalles_orden')
    op.drop_table('detalles_orden')
    op.drop_index('idx_asistencias_usuario', table_name='asistencias')
    op.drop_index('idx_asistencias_fecha', table_name='asistencias', postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.drop_index('idx_asistencias_evento', table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index('idx_usuarios_roles_usuario', table_name='usuarios_roles')
    op.drop_index('idx_usuarios_roles_expiry', table_name='usuarios_roles', postgresql_where=sa.text('valido_hasta IS NOT NULL'))
    op.drop_table('usuarios_roles')
    op.drop_table('usuarios_categorias')
    op.drop_index('idx_reservas_instalacion_tiempo', table_name='reservas_instalaciones', postgresql_where=sa.text("estado IN ('bloqueada', 'confirmada')"))
    op.drop_table('reservas_instalaciones')
    op.drop_index('idx_ordenes_usuario', table_name='ordenes')
    op.drop_index('idx_ordenes_expira_at', table_name='ordenes', postgresql_where=sa.text("estado = 'pendiente_verificacion'"))
    op.drop_index('idx_ordenes_estado', table_name='ordenes', postgresql_where=sa.text("estado = 'pendiente_verificacion'"))
    op.drop_table('ordenes')
    op.drop_index('idx_notificaciones_usuario_no_leidas', table_name='notificaciones', postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.drop_table('notificaciones')
    op.drop_index('idx_eventos_fecha', table_name='eventos', postgresql_ops={'fecha_inicio': 'DESC'})
    op.drop_index('idx_eventos_estado', table_name='eventos', postgresql_where=sa.text("estado IN ('programado', 'en_curso')"))
    op.drop_table('eventos')
    op.drop_index('idx_audit_log_tabla', table_name='audit_log')
    op.drop_index('idx_audit_log_created_at', table_name='audit_log', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_audit_log_actor', table_name='audit_log')
    op.drop_index('idx_audit_log_accion', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_usuarios_search', table_name='usuarios', postgresql_using='gin')
    op.drop_index('idx_usuarios_qr_token', table_name='usuarios')
    op.drop_index('idx_usuarios_fecha_baja', table_name='usuarios', postgresql_where=sa.text('fecha_baja IS NULL'))
    op.drop_index('idx_usuarios_dni', table_name='usuarios')
    op.drop_index('idx_usuarios_apellido', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_index('idx_productos_categoria', table_name='productos_servicios', postgresql_where=sa.text('es_activo = TRUE'))
    op.drop_table('productos_servicios')
    op.drop_table('configuracion_global')
    op.drop_table('categorias_deportivas')
    # ### end Alembic commands ###
