"""initial_schema

Revision ID: cac4e912d733
Revises: 
Create Date: 2026-06-29 13:08:36.139154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cac4e912d733'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias_deportivas')
    op.drop_table('usuarios_categorias')
    op.drop_index(op.f('idx_reservas_instalacion_tiempo'), table_name='reservas_instalaciones', postgresql_where="((estado)::text = ANY ((ARRAY['bloqueada'::character varying, 'confirmada'::character varying])::text[]))")
    op.drop_table('reservas_instalaciones')
    op.drop_index(op.f('idx_configuracion_global_singleton'), table_name='configuracion_global')
    op.drop_table('configuracion_global')
    op.drop_index(op.f('idx_asistencias_evento'), table_name='asistencias')
    op.drop_index(op.f('idx_asistencias_fecha'), table_name='asistencias')
    op.drop_index(op.f('idx_asistencias_usuario'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_table('roles')
    op.drop_index(op.f('idx_notificaciones_usuario_no_leidas'), table_name='notificaciones', postgresql_where='(leida = false)')
    op.drop_table('notificaciones')
    op.drop_index(op.f('idx_audit_log_accion'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_actor'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_tabla'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('idx_detalles_orden_orden'), table_name='detalles_orden')
    op.drop_index(op.f('idx_detalles_orden_producto'), table_name='detalles_orden')
    op.drop_table('detalles_orden')
    op.drop_index(op.f('idx_usuarios_apellido'), table_name='usuarios')
    op.drop_index(op.f('idx_usuarios_dni'), table_name='usuarios')
    op.drop_index(op.f('idx_usuarios_fecha_baja'), table_name='usuarios', postgresql_where='(fecha_baja IS NULL)')
    op.drop_index(op.f('idx_usuarios_qr_token'), table_name='usuarios')
    op.drop_index(op.f('idx_usuarios_search'), table_name='usuarios', postgresql_using='gin')
    op.drop_table('usuarios')
    op.drop_index(op.f('idx_usuarios_roles_expiry'), table_name='usuarios_roles', postgresql_where='(valido_hasta IS NOT NULL)')
    op.drop_index(op.f('idx_usuarios_roles_usuario'), table_name='usuarios_roles')
    op.drop_table('usuarios_roles')
    op.drop_index(op.f('idx_ordenes_estado'), table_name='ordenes', postgresql_where="((estado)::text = 'pendiente_verificacion'::text)")
    op.drop_index(op.f('idx_ordenes_expira_at'), table_name='ordenes', postgresql_where="((estado)::text = 'pendiente_verificacion'::text)")
    op.drop_index(op.f('idx_ordenes_usuario'), table_name='ordenes')
    op.drop_table('ordenes')
    op.drop_index(op.f('idx_eventos_estado'), table_name='eventos', postgresql_where="((estado)::text = ANY ((ARRAY['programado'::character varying, 'en_curso'::character varying])::text[]))")
    op.drop_index(op.f('idx_eventos_fecha'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('idx_productos_categoria'), table_name='productos_servicios', postgresql_where='(es_activo = true)')
    op.drop_table('productos_servicios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_servicios',
    sa.Column('id_producto', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('precio_actual', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True, comment='NULL para servicios sin stock físico (cuota social). Integer para indumentaria.'),
    sa.Column('es_activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('imagen_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creado_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actualizado_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("categoria::text = ANY (ARRAY['cuota_social'::character varying, 'alquiler'::character varying, 'indumentaria'::character varying, 'otro'::character varying]::text[])", name=op.f('productos_servicios_categoria_check')),
    sa.PrimaryKeyConstraint('id_producto', name=op.f('productos_servicios_pkey'))
    )
    op.create_index(op.f('idx_productos_categoria'), 'productos_servicios', ['categoria'], unique=False, postgresql_where='(es_activo = true)')
    op.create_table('eventos',
    sa.Column('id_evento', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ubicacion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=30), server_default=sa.text("'programado'::character varying"), autoincrement=False, nullable=False),
    sa.Column('creado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creado_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("estado::text = ANY (ARRAY['programado'::character varying, 'en_curso'::character varying, 'finalizado'::character varying, 'cancelado'::character varying]::text[])", name=op.f('eventos_estado_check')),
    sa.CheckConstraint("tipo::text = ANY (ARRAY['partido'::character varying, 'torneo'::character varying, 'entrenamiento'::character varying, 'institucional'::character varying, 'otro'::character varying]::text[])", name=op.f('eventos_tipo_check')),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], name=op.f('eventos_creado_por_fkey')),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias_deportivas.id_categoria'], name=op.f('eventos_id_categoria_fkey')),
    sa.PrimaryKeyConstraint('id_evento', name=op.f('eventos_pkey'))
    )
    op.create_index(op.f('idx_eventos_fecha'), 'eventos', [sa.literal_column('fecha_inicio DESC')], unique=False)
    op.create_index(op.f('idx_eventos_estado'), 'eventos', ['estado'], unique=False, postgresql_where="((estado)::text = ANY ((ARRAY['programado'::character varying, 'en_curso'::character varying])::text[]))")
    op.create_table('ordenes',
    sa.Column('id_orden', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=40), server_default=sa.text("'pendiente_verificacion'::character varying"), autoincrement=False, nullable=False),
    sa.Column('monto_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('comprobante_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motivo_rechazo', sa.TEXT(), autoincrement=False, nullable=True, comment='Requerido si estado = rechazada. El admin debe explicar por qué (ej: monto no coincide).'),
    sa.Column('aprobada_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aprobada_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expira_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(now() + '48:00:00'::interval)"), autoincrement=False, nullable=False, comment='Un job programado revisa periódicamente y marca como expirada las órdenes vencidas, liberando stock y reservas.'),
    sa.Column('notas_admin', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("estado::text = ANY (ARRAY['pendiente_verificacion'::character varying, 'aprobada'::character varying, 'rechazada'::character varying, 'cancelada_socio'::character varying, 'expirada'::character varying]::text[])", name=op.f('ordenes_estado_check')),
    sa.ForeignKeyConstraint(['aprobada_por'], ['usuarios.id_usuario'], name=op.f('ordenes_aprobada_por_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('ordenes_id_usuario_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_orden', name=op.f('ordenes_pkey'))
    )
    op.create_index(op.f('idx_ordenes_usuario'), 'ordenes', ['id_usuario'], unique=False)
    op.create_index(op.f('idx_ordenes_expira_at'), 'ordenes', ['expira_at'], unique=False, postgresql_where="((estado)::text = 'pendiente_verificacion'::text)")
    op.create_index(op.f('idx_ordenes_estado'), 'ordenes', ['estado'], unique=False, postgresql_where="((estado)::text = 'pendiente_verificacion'::text)")
    op.create_table('usuarios_roles',
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_rol', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valido_hasta', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Para admin_temporal: se completa con la fecha de cierre del evento. Job programado lo limpia.'),
    sa.Column('asignado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asignado_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asignado_por'], ['usuarios.id_usuario'], name=op.f('usuarios_roles_asignado_por_fkey')),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], name=op.f('usuarios_roles_id_rol_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('usuarios_roles_id_usuario_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol', name=op.f('usuarios_roles_pkey'))
    )
    op.create_index(op.f('idx_usuarios_roles_usuario'), 'usuarios_roles', ['id_usuario'], unique=False)
    op.create_index(op.f('idx_usuarios_roles_expiry'), 'usuarios_roles', ['valido_hasta'], unique=False, postgresql_where='(valido_hasta IS NOT NULL)')
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('foto_perfil_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requiere_cambio_password', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='TRUE para socios migrados desde Excel. El frontend bloquea navegación hasta que cambien la clave.'),
    sa.Column('ultimo_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('qr_token', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False, comment='Token opaco UUID. El QR nunca expone datos planos. Se rota al cambiar estado financiero.'),
    sa.Column('qr_generado_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('mes_cubierto_hasta', sa.DATE(), autoincrement=False, nullable=True, comment='Si pagó por adelantado, queda inmune a aumentos hasta esta fecha.'),
    sa.Column('deuda_historica_meses', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Cantidad de meses adeudados. Deuda total = deuda_historica_meses × valor_cuota_base_vigente.'),
    sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_ingreso', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('fecha_baja', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_directivo', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('nombre_completo_search', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.Column('id_titular', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('push_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creado_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actualizado_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_titular'], ['usuarios.id_usuario'], name=op.f('usuarios_id_titular_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('dni', name=op.f('usuarios_dni_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('email', name=op.f('usuarios_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('qr_token', name=op.f('usuarios_qr_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_usuarios_search'), 'usuarios', ['nombre_completo_search'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_usuarios_qr_token'), 'usuarios', ['qr_token'], unique=False)
    op.create_index(op.f('idx_usuarios_fecha_baja'), 'usuarios', ['fecha_baja'], unique=False, postgresql_where='(fecha_baja IS NULL)')
    op.create_index(op.f('idx_usuarios_dni'), 'usuarios', ['dni'], unique=False)
    op.create_index(op.f('idx_usuarios_apellido'), 'usuarios', ['apellido'], unique=False)
    op.create_table('detalles_orden',
    sa.Column('id_detalle', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_orden', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('precio_unitario_historico', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False, comment='CRÍTICO: al aprobar la orden, usar SIEMPRE este valor, nunca precio_actual del producto.'),
    sa.Column('mes_referencia', sa.DATE(), autoincrement=False, nullable=True, comment='Para cuotas: almacena el mes al que corresponde el pago (2025-06-01 = Junio 2025).'),
    sa.Column('id_reserva', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('cantidad > 0', name=op.f('detalles_orden_cantidad_check')),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes.id_orden'], name=op.f('detalles_orden_id_orden_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos_servicios.id_producto'], name=op.f('detalles_orden_id_producto_fkey')),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas_instalaciones.id_reserva'], name=op.f('detalles_orden_id_reserva_fkey')),
    sa.PrimaryKeyConstraint('id_detalle', name=op.f('detalles_orden_pkey'))
    )
    op.create_index(op.f('idx_detalles_orden_producto'), 'detalles_orden', ['id_producto'], unique=False)
    op.create_index(op.f('idx_detalles_orden_orden'), 'detalles_orden', ['id_orden'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('usuario_actor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('registro_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_origen', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_actor'], ['usuarios.id_usuario'], name=op.f('audit_log_usuario_actor_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey')),
    comment='Tabla de solo escritura. Nunca se actualiza ni elimina. Trazabilidad completa del sistema.'
    )
    op.create_index(op.f('idx_audit_log_tabla'), 'audit_log', ['tabla_afectada', 'registro_id'], unique=False)
    op.create_index(op.f('idx_audit_log_created_at'), 'audit_log', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_log_actor'), 'audit_log', ['usuario_actor'], unique=False)
    op.create_index(op.f('idx_audit_log_accion'), 'audit_log', ['accion'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cuerpo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('leida', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('referencia_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('referencia_tabla', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("tipo::text = ANY (ARRAY['orden_aprobada'::character varying, 'orden_rechazada'::character varying, 'cuota_vencida'::character varying, 'reserva_confirmada'::character varying, 'reserva_cancelada'::character varying, 'rol_asignado'::character varying, 'rol_removido'::character varying, 'convocatoria_partido'::character varying, 'sistema'::character varying]::text[])", name=op.f('notificaciones_tipo_check')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('notificaciones_id_usuario_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notificacion', name=op.f('notificaciones_pkey'))
    )
    op.create_index(op.f('idx_notificaciones_usuario_no_leidas'), 'notificaciones', ['id_usuario', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(leida = false)')
    op.create_table('roles',
    sa.Column('id_rol', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('peso_jerarquico', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Permite ordenar y comparar roles. Admin General = 100, Socio = 10, Invitado = 1.'),
    sa.Column('es_activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_rol', name=op.f('roles_pkey')),
    sa.UniqueConstraint('nombre', name=op.f('roles_nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('asistencias',
    sa.Column('id_asistencia', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_evento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_hora_ingreso', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('metodo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('registrado_por', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado_financiero_snapshot', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.CheckConstraint("estado_financiero_snapshot::text = ANY (ARRAY['al_dia'::character varying, 'moroso'::character varying]::text[])", name=op.f('asistencias_estado_financiero_snapshot_check')),
    sa.CheckConstraint("metodo::text = ANY (ARRAY['QR'::character varying, 'DNI'::character varying]::text[])", name=op.f('asistencias_metodo_check')),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], name=op.f('asistencias_id_evento_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('asistencias_id_usuario_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id_usuario'], name=op.f('asistencias_registrado_por_fkey')),
    sa.PrimaryKeyConstraint('id_asistencia', name=op.f('asistencias_pkey')),
    comment='Registro inmutable de ingresos. El campo estado_financiero_snapshot guarda el estado al momento del escaneo.'
    )
    op.create_index(op.f('idx_asistencias_usuario'), 'asistencias', ['id_usuario'], unique=False)
    op.create_index(op.f('idx_asistencias_fecha'), 'asistencias', [sa.literal_column('fecha_hora_ingreso DESC')], unique=False)
    op.create_index(op.f('idx_asistencias_evento'), 'asistencias', ['id_evento'], unique=False)
    op.create_table('configuracion_global',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('valor_cuota_base', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False, comment='Al modificar este campo, la deuda de todos los morosos se recalcula dinámicamente.'),
    sa.Column('meses_antiguedad_beneficio', sa.INTEGER(), server_default=sa.text('6'), autoincrement=False, nullable=False),
    sa.Column('descuento_beneficio', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('15'), autoincrement=False, nullable=False, comment='Porcentaje (0-100) de descuento en alquiler de instalaciones por antigüedad.'),
    sa.Column('actualizado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actualizado_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id_usuario'], name=op.f('fk_config_actualizado_por'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('configuracion_global_pkey')),
    comment='Cerebro financiero del sistema. Una sola fila. Solo el Admin General puede modificarla.'
    )
    op.create_index(op.f('idx_configuracion_global_singleton'), 'configuracion_global', [sa.literal_column('(true)')], unique=True)
    op.create_table('reservas_instalaciones',
    sa.Column('id_reserva', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instalacion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=30), server_default=sa.text("'bloqueada'::character varying"), autoincrement=False, nullable=False),
    sa.Column('id_orden', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creado_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("estado::text = ANY (ARRAY['bloqueada'::character varying, 'confirmada'::character varying, 'liberada'::character varying, 'expirada'::character varying]::text[])", name=op.f('reservas_instalaciones_estado_check')),
    sa.CheckConstraint('fecha_fin > fecha_inicio', name=op.f('chk_reserva_fechas')),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes.id_orden'], name=op.f('fk_reservas_orden'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos_servicios.id_producto'], name=op.f('reservas_instalaciones_id_producto_fkey')),
    sa.PrimaryKeyConstraint('id_reserva', name=op.f('reservas_instalaciones_pkey')),
    comment='Una reserva se crea en estado bloqueada al generar la orden. Pasa a confirmada al aprobarla, y a liberada si se rechaza o expira.'
    )
    op.create_index(op.f('idx_reservas_instalacion_tiempo'), 'reservas_instalaciones', ['instalacion', 'fecha_inicio', 'fecha_fin'], unique=False, postgresql_where="((estado)::text = ANY ((ARRAY['bloqueada'::character varying, 'confirmada'::character varying])::text[]))")
    op.create_table('usuarios_categorias',
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temporada', sa.VARCHAR(length=10), server_default=sa.text("to_char((CURRENT_DATE)::timestamp with time zone, 'YYYY'::text)"), autoincrement=False, nullable=False),
    sa.Column('es_capitan', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias_deportivas.id_categoria'], name=op.f('usuarios_categorias_id_categoria_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('usuarios_categorias_id_usuario_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_categoria', 'temporada', name=op.f('usuarios_categorias_pkey'))
    )
    op.create_table('categorias_deportivas',
    sa.Column('id_categoria', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('es_activa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_categoria', name=op.f('categorias_deportivas_pkey')),
    sa.UniqueConstraint('nombre', name=op.f('categorias_deportivas_nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
