"""add_dia_vencimiento_cuota

Revision ID: d8a4662bbaa0
Revises: c03285f75d23
Create Date: 2026-07-03 23:03:17.482998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a4662bbaa0'
down_revision: Union[str, Sequence[str], None] = 'c03285f75d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_asistencias_fecha'), table_name='asistencias')
    op.create_index('idx_asistencias_fecha', 'asistencias', ['fecha_hora_ingreso'], unique=False, postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.drop_index(op.f('idx_audit_log_created_at'), table_name='audit_log')
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.add_column('configuracion_global', sa.Column('dia_vencimiento_cuota', sa.Integer(), server_default=sa.text('10'), nullable=False, comment='Día del mes en que vence el período de cobertura del socio (1–28). Por ejemplo: 10 → el acceso del socio expira el día 10 de cada mes. Limitado a 28 para evitar fechas inexistentes en febrero.'))
    op.drop_index(op.f('idx_eventos_fecha'), table_name='eventos')
    op.create_index('idx_eventos_fecha', 'eventos', ['fecha_inicio'], unique=False, postgresql_ops={'fecha_inicio': 'DESC'})
    op.drop_index(op.f('idx_notificaciones_usuario_no_leidas'), table_name='notificaciones', postgresql_where='(leida = false)')
    op.create_index('idx_notificaciones_usuario_no_leidas', 'notificaciones', ['id_usuario', 'created_at'], unique=False, postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.alter_column('usuarios', 'mes_cubierto_hasta',
               existing_type=sa.DATE(),
               comment="Fecha exacta hasta la cual el socio tiene el acceso habilitado. NULL = nunca pagó (socio nuevo o sin cuotas aprobadas). Evaluación de estado: CURRENT_DATE <= mes_cubierto_hasta → 'al_dia'. El backend calcula esta fecha al aprobar una orden de cuota_social:   nueva_fecha = MAX(mes_cubierto_hasta_actual, hoy)               + meses_pagados meses               con día = dia_vencimiento_cuota de ConfiguracionGlobal. Si el socio pagó por adelantado, queda inmune a aumentos de precio hasta esta fecha (el precio ya fue congelado en precio_unitario_historico).",
               existing_comment='Si pagó por adelantado, queda inmune a aumentos hasta esta fecha.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'mes_cubierto_hasta',
               existing_type=sa.DATE(),
               comment='Si pagó por adelantado, queda inmune a aumentos hasta esta fecha.',
               existing_comment="Fecha exacta hasta la cual el socio tiene el acceso habilitado. NULL = nunca pagó (socio nuevo o sin cuotas aprobadas). Evaluación de estado: CURRENT_DATE <= mes_cubierto_hasta → 'al_dia'. El backend calcula esta fecha al aprobar una orden de cuota_social:   nueva_fecha = MAX(mes_cubierto_hasta_actual, hoy)               + meses_pagados meses               con día = dia_vencimiento_cuota de ConfiguracionGlobal. Si el socio pagó por adelantado, queda inmune a aumentos de precio hasta esta fecha (el precio ya fue congelado en precio_unitario_historico).",
               existing_nullable=True)
    op.drop_index('idx_notificaciones_usuario_no_leidas', table_name='notificaciones', postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_notificaciones_usuario_no_leidas'), 'notificaciones', ['id_usuario', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(leida = false)')
    op.drop_index('idx_eventos_fecha', table_name='eventos', postgresql_ops={'fecha_inicio': 'DESC'})
    op.create_index(op.f('idx_eventos_fecha'), 'eventos', [sa.literal_column('fecha_inicio DESC')], unique=False)
    op.drop_column('configuracion_global', 'dia_vencimiento_cuota')
    op.drop_index('idx_audit_log_created_at', table_name='audit_log', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_audit_log_created_at'), 'audit_log', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_asistencias_fecha', table_name='asistencias', postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.create_index(op.f('idx_asistencias_fecha'), 'asistencias', [sa.literal_column('fecha_hora_ingreso DESC')], unique=False)
    # ### end Alembic commands ###
