"""reservas: saldo_a_favor, id_usuario/notas/reintegro en reservas, tabla reintegros_qr

Revision ID: e0851f0fdd20
Revises: 5e5c11d73200
Create Date: 2026-07-21 15:10:28.777550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0851f0fdd20'
down_revision: Union[str, Sequence[str], None] = '5e5c11d73200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reintegros_qr',
    sa.Column('id_reintegro', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma', sa.String(length=20), server_default=sa.text("'pendiente'"), nullable=False, comment="'pendiente' | 'saldo_a_favor' | 'efectivo' | 'transferencia'"),
    sa.Column('escaneado_por', sa.Integer(), nullable=False, comment='Operador (portero_cancha) que hizo el escaneo.'),
    sa.Column('escaneado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("forma IN ('pendiente', 'saldo_a_favor', 'efectivo', 'transferencia')", name='chk_reintegro_forma'),
    sa.ForeignKeyConstraint(['escaneado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas_instalaciones.id_reserva'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_reintegro'),
    sa.UniqueConstraint('id_reserva', 'id_usuario', name='uq_reintegro_reserva_usuario')
    )
    op.create_index('idx_reintegros_reserva', 'reintegros_qr', ['id_reserva'], unique=False)
    op.drop_index(op.f('idx_asistencias_fecha'), table_name='asistencias')
    op.create_index('idx_asistencias_fecha', 'asistencias', ['fecha_hora_ingreso'], unique=False, postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.drop_index(op.f('idx_audit_log_created_at'), table_name='audit_log')
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_eventos_fecha'), table_name='eventos')
    op.create_index('idx_eventos_fecha', 'eventos', ['fecha_inicio'], unique=False, postgresql_ops={'fecha_inicio': 'DESC'})
    op.drop_index(op.f('idx_notificaciones_usuario_no_leidas'), table_name='notificaciones', postgresql_where='(leida = false)')
    op.create_index('idx_notificaciones_usuario_no_leidas', 'notificaciones', ['id_usuario', 'created_at'], unique=False, postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.add_column('reservas_instalaciones', sa.Column('id_usuario', sa.Integer(), nullable=True, comment='Socio que generó la pre-reserva (dueño del turno en el carrito). NULL en franjas viejas o si el usuario se dio de baja.'))
    op.add_column('reservas_instalaciones', sa.Column('notas', sa.Text(), nullable=True, comment='Nombre del grupo/evento, aclaración libre del admin.'))
    op.add_column('reservas_instalaciones', sa.Column('num_socios_esperados', sa.Integer(), nullable=True, comment='Cuántos socios se esperan en el turno. Base para calcular monto_reintegro_unitario.'))
    op.add_column('reservas_instalaciones', sa.Column('monto_reintegro_unitario', sa.Numeric(precision=10, scale=2), nullable=True, comment='Reintegro fijo por socio que escanea QR en este turno. Lo fija el admin (default sugerido = precio_reserva × 0.20 / num_socios_esperados) y queda congelado: el escaneo simplemente lo copia, no lo recalcula.'))
    op.create_foreign_key(None, 'reservas_instalaciones', 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='SET NULL')
    op.add_column('usuarios', sa.Column('saldo_a_favor', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False, comment="Crédito interno del socio. Se acredita automáticamente por ReintegroQR.forma='saldo_a_favor' o por suspensión de una reserva confirmada (lluvia, etc). Se descuenta en el checkout antes de pedir comprobante — esa resta la hace el router de carrito, no un trigger de este modelo."))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'saldo_a_favor')
    op.drop_constraint(None, 'reservas_instalaciones', type_='foreignkey')
    op.drop_column('reservas_instalaciones', 'monto_reintegro_unitario')
    op.drop_column('reservas_instalaciones', 'num_socios_esperados')
    op.drop_column('reservas_instalaciones', 'notas')
    op.drop_column('reservas_instalaciones', 'id_usuario')
    op.drop_index('idx_notificaciones_usuario_no_leidas', table_name='notificaciones', postgresql_where=sa.text('leida = FALSE'), postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_notificaciones_usuario_no_leidas'), 'notificaciones', ['id_usuario', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(leida = false)')
    op.drop_index('idx_eventos_fecha', table_name='eventos', postgresql_ops={'fecha_inicio': 'DESC'})
    op.create_index(op.f('idx_eventos_fecha'), 'eventos', [sa.literal_column('fecha_inicio DESC')], unique=False)
    op.drop_index('idx_audit_log_created_at', table_name='audit_log', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_audit_log_created_at'), 'audit_log', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_asistencias_fecha', table_name='asistencias', postgresql_ops={'fecha_hora_ingreso': 'DESC'})
    op.create_index(op.f('idx_asistencias_fecha'), 'asistencias', [sa.literal_column('fecha_hora_ingreso DESC')], unique=False)
    op.drop_index('idx_reintegros_reserva', table_name='reintegros_qr')
    op.drop_table('reintegros_qr')
    # ### end Alembic commands ###
